export const LOGIN_REQUEST ="LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCESS ="LOGIN_REQUEST_SUCESS";
export const LOGIN_REQUEST_FAIL ="LOGIN_REQUEST_FAIL";
export const LOGOUT_REQUEST ="LOGOUT_REQUEST";
export const LOGOUT_REQUEST_SUCESS="LOGOUT_REQUEST_SUCESS";
