export const stateActionTypes = {
    STATE_LIST_REQUEST: "STATE_LIST_REQUEST",
    STATE_LIST_REQUEST_SUCCESS: "STATE_LIST_REQUEST_SUCCESS",
    STATE_LIST_REQUEST_FAILURE: "STATE_LIST_REQUEST_FAILURE",

    STATE_ADD_REQUEST: "STATE_ADD_REQUEST",
    STATE_ADD_REQUEST_SUCCESS: "STATE_ADD_REQUEST_SUCCESS",
    STATE_ADD_REQUEST_FAILURE: "STATE_ADD_REQUEST_FAILURE",

    STATE_EDIT_REQUEST: "STATE_EDIT_REQUEST",
    STATE_EDIT_REQUEST_SUCCESS: "STATE_EDIT_REQUEST_SUCCESS",
    STATE_EDIT_REQUEST_FAILURE: "STATE_EDIT_REQUEST_FAILURE"
}